CREATE TABLE categorias (
   ID_CATEGORIA int(11) NOT NULL AUTO_INCREMENT,
   DESC_CATEGORIA varchar(64) NOT NULL,
   DTRG_CATEGORIA timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CATEGORIA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE log_pedidos (
ID_LPEDIDOS INT(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_MESA INT(12) NOT NULL,
ID_PEDIDO INT(12) NOT NULL,
LOG_DATA TIMESTAMP NOT NULL,
CONSTRAINT FK_LP_PEDIDOS FOREIGN KEY(ID_PEDIDO) REFERENCES pedido(ID_PEDIDO)
);

SELECT * FROM pedido p
INNER JOIN log_pedidos l
ON p.ID_PEDIDO = l.ID_PEDIDO;

INSERT INTO log_pedidos (ID_MESA, ID_PEDIDO, LOG_DATA)
VALUES(1, 1, CURRENT_TIMESTAMP);


INSERT INTO pedido(ID_CLIENTE, TIPO_PEDIDO, VAL_TOTAL, STATUS_PEDIDO)
VALUES (1, "LOCAL", 0, "ABERTO");

ALTER TABLE pedido 
ADD STATUS_PEDIDO VARCHAR(40);